export interface ActionItem {
  id: string
  meeting_id: string
  task: string
  owner: string
  due_date: string | null
  priority: 'low' | 'medium' | 'high'
  status: 'open' | 'done'
  created_at: string
}

export interface Meeting {
  id: string
  title: string
  raw_transcript: string
  created_at: string
}

// Escapes CSV cell value to handle commas, quotes, and newlines
function escapeCSV(val: string): string {
  if (val === null || val === undefined) return ''
  const formatted = String(val).replace(/"/g, '""')
  if (formatted.includes(',') || formatted.includes('\n') || formatted.includes('"')) {
    return `"${formatted}"`
  }
  return formatted
}

export function exportToCSV(meetingTitle: string, items: ActionItem[]) {
  const headers = ['Task', 'Owner', 'Due Date', 'Priority', 'Status']
  const rows = items.map(item => [
    item.task,
    item.owner,
    item.due_date || 'N/A',
    item.priority.toUpperCase(),
    item.status === 'done' ? 'Completed' : 'Open'
  ])

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(escapeCSV).join(','))
  ].join('\n')

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  
  const sanitizedTitle = meetingTitle.toLowerCase().replace(/[^a-z0-9]+/g, '_')
  link.setAttribute('href', url)
  link.setAttribute('download', `recapai_actions_${sanitizedTitle}.csv`)
  link.style.visibility = 'hidden'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

export function exportToMarkdown(meeting: Meeting, items: ActionItem[]) {
  const dateStr = new Date(meeting.created_at).toLocaleDateString(undefined, {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })

  let mdContent = `# Meeting Action Items: ${meeting.title}\n`
  mdContent += `**Date:** ${dateStr}\n\n`
  mdContent += `## Summary of Action Items\n\n`
  
  const openItems = items.filter(i => i.status === 'open')
  const doneItems = items.filter(i => i.status === 'done')
  
  mdContent += `- **Total Tasks:** ${items.length}\n`
  mdContent += `- **Open Tasks:** ${openItems.length}\n`
  mdContent += `- **Completed Tasks:** ${doneItems.length}\n\n`

  mdContent += `## Action Items Table\n\n`
  mdContent += `| Status | Task | Owner | Due Date | Priority |\n`
  mdContent += `| :--- | :--- | :--- | :--- | :--- |\n`
  
  items.forEach(item => {
    const statusIcon = item.status === 'done' ? '✅ Completed' : '⬜ Open'
    const dueDate = item.due_date ? item.due_date : 'N/A'
    const priorityIcon = item.priority === 'high' ? '🔴 High' : item.priority === 'medium' ? '🟡 Medium' : '🔵 Low'
    mdContent += `| ${statusIcon} | ${item.task} | ${item.owner} | ${dueDate} | ${priorityIcon} |\n`
  })

  mdContent += `\n---\n*Generated by RecapAI - AI-Powered Meeting Extractions*`

  const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  
  const sanitizedTitle = meeting.title.toLowerCase().replace(/[^a-z0-9]+/g, '_')
  link.setAttribute('href', url)
  link.setAttribute('download', `recapai_summary_${sanitizedTitle}.md`)
  link.style.visibility = 'hidden'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}
