export interface ActionItem {
  id: string
  meeting_id: string
  task: string
  owner: string
  due_date: string | null
  priority: 'low' | 'medium' | 'high'
  status: 'open' | 'done'
  created_at: string
}

export interface Meeting {
  id: string
  title: string
  raw_transcript: string
  created_at: string
  user_id?: string
}

// Escapes CSV cell value to handle commas, quotes, and newlines
function escapeCSV(val: string): string {
  if (val === null || val === undefined) return ''
  const formatted = String(val).replace(/"/g, '""')
  if (formatted.includes(',') || formatted.includes('\n') || formatted.includes('"')) {
    return `"${formatted}"`
  }
  return formatted
}

/**
 * Universal Mobile & Desktop file download helper
 */
function downloadFile(content: string, filename: string, mimeType: string) {
  try {
    const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` })
    const url = URL.createObjectURL(blob)

    // Attempt Web Share API first if supported for files (iOS Safari / Android Native Share)
    if (typeof navigator !== 'undefined' && 'canShare' in navigator && navigator.canShare) {
      try {
        const file = new File([blob], filename, { type: mimeType })
        if (navigator.canShare({ files: [file] })) {
          navigator.share({
            files: [file],
            title: filename,
          }).then(() => {
            URL.revokeObjectURL(url)
          }).catch(() => {
            // Fallback to standard anchor trigger if user cancels share dialog
            triggerAnchorDownload(url, filename)
          })
          return
        }
      } catch (err) {
        console.warn("Web Share API error, falling back to direct download:", err)
      }
    }

    triggerAnchorDownload(url, filename)
  } catch (error) {
    console.error("Export file download error:", error)
  }
}

function triggerAnchorDownload(url: string, filename: string) {
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.setAttribute('target', '_blank')
  link.style.display = 'none'

  document.body.appendChild(link)
  
  // Trigger click
  link.click()

  // Clean up
  setTimeout(() => {
    if (document.body.contains(link)) {
      document.body.removeChild(link)
    }
    URL.revokeObjectURL(url)
  }, 1000)
}

export function exportToCSV(meetingTitle: string, items: ActionItem[]) {
  const headers = ['Task', 'Owner', 'Due Date', 'Priority', 'Status']
  const rows = items.map(item => [
    item.task,
    item.owner,
    item.due_date || 'N/A',
    item.priority.toUpperCase(),
    item.status === 'done' ? 'Completed' : 'Open'
  ])

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(escapeCSV).join(','))
  ].join('\n')

  const sanitizedTitle = meetingTitle.toLowerCase().replace(/[^a-z0-9]+/g, '_')
  const filename = `recapai_actions_${sanitizedTitle || 'summary'}.csv`

  downloadFile(csvContent, filename, 'text/csv')
}

export function exportToMarkdown(meeting: Meeting, items: ActionItem[]) {
  const dateStr = new Date(meeting.created_at).toLocaleDateString(undefined, {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })

  let mdContent = `# Meeting Action Items: ${meeting.title}\n`
  mdContent += `**Date:** ${dateStr}\n\n`
  mdContent += `## Summary of Action Items\n\n`
  
  const openItems = items.filter(i => i.status === 'open')
  const doneItems = items.filter(i => i.status === 'done')
  
  mdContent += `- **Total Tasks:** ${items.length}\n`
  mdContent += `- **Open Tasks:** ${openItems.length}\n`
  mdContent += `- **Completed Tasks:** ${doneItems.length}\n\n`

  mdContent += `## Action Items Table\n\n`
  mdContent += `| Status | Task | Owner | Due Date | Priority |\n`
  mdContent += `| :--- | :--- | :--- | :--- | :--- |\n`
  
  items.forEach(item => {
    const statusIcon = item.status === 'done' ? '✅ Completed' : '⬜ Open'
    const dueDate = item.due_date ? item.due_date : 'N/A'
    const priorityIcon = item.priority === 'high' ? '🔴 High' : item.priority === 'medium' ? '🟡 Medium' : '🔵 Low'
    mdContent += `| ${statusIcon} | ${item.task} | ${item.owner} | ${dueDate} | ${priorityIcon} |\n`
  })

  mdContent += `\n---\n*Generated by RecapAI - AI-Powered Meeting Extractions*`

  const sanitizedTitle = meeting.title.toLowerCase().replace(/[^a-z0-9]+/g, '_')
  const filename = `recapai_summary_${sanitizedTitle || 'summary'}.md`

  downloadFile(mdContent, filename, 'text/markdown')
}
